### ISSUE TITLE
How are you supposed to use it?

### ISSUE THREAD

**Issue by User670** [andrew-gardener/mota-translator#1]
I installed the script, opened the site, and it asked me to input script key and API key (I typed some random strings for both firlds). And I opened a game, and all text (other than the title screen texts, which are apparently a different thing from the main game canvas) disappeared. :-/

Is there an instruction on how to use this thing?

**Comment by andrew-gardener** [comment]
Sorry about that. Wasn't sure if anyone else would actually use this.

I used `https://translate.yandex.com/` for the translator since it offers api keys for free translation (google translate which is a bit better sadly requires you to setup a console account with credit card info which I wanted to avoid). 

I'll try and add some detailed easy to follow instructions soon.

If you want to try and use it before then, just
- go to https://translate.yandex.com/ 
- click login
- click register
- create an account (probably don't use important email or passwords since its a Russian website and I can't vouch for if its super safe or not)
- after being logged in you should see something about api keys (create a new one and enter that info). Can't give more details about this part right now since I'm at work.

**Comment by User670** [comment]
Ohh thanks.

Actually I'm a Chinese and I read Chinese, but I'm just curious about what this is and what it does :-P 

~~guess they won't add actual localization/internationalization support in their games hm~~

**Comment by andrew-gardener** [comment]
Its just something I threw together to translate the canvas rendered text since you can't use google translate plugin/extensions on it (so I can easily translate a few UI items without this but the core game was completely unreadable to me). 

It doesn't work well on a few of them due to the delay between translations and how the text is rendered (slow reveal text) but it stores previously translated text in local storage so it will display text alright when reloading and triggering the text again.

**Comment by andrew-gardener** [comment]
@user670  I've updated the Readme https://github.com/andrew-gardener/mota-translator

> ~~guess they won't add actual localization/internationalization support in their games hm~~ 

I honestly have no idea if they have plans to do anything supporting different languages (haven't tried talking to them at all). I mostly made this as a quick little workaround so that I can play their games since I really love this type of game and there aren't that many like it in English.

**Comment by User670** [comment]
Nope. Nooooope. They are *not* going to make that any international at all.

~~if anyone ever wanted to make an int'l version of anything like that they can just go  modify their "framework/template" thing so that all things are in another language.~~

~~remember to edit every string tho, their strings are hard coded~~
